[HOPSWORKS-1813] Put back conda environment import
logicalclocks/hopsworks-chef pull request #479
Opened 2020-08-20 08:45 UTC by robzor92

2020-08-20 08:53 UTC, tkakantousis requested changes

2020-08-20 08:53 UTC, tkakantousis commented on files/default/sql/ddl/updates/undo/1.4.0__undo.sql
> +ALTER TABLE `hopsworks`.`conda_commands` CHANGE `error_message` `error_message` VARCHAR(6000) COLLATE latin1_general_cs DEFAULT NULL;
```suggestion
ALTER TABLE `hopsworks`.`conda_commands` CHANGE `error_message` `error_message` VARCHAR(11000) COLLATE latin1_general_cs DEFAULT NULL;
```

2020-08-20 15:41 UTC, robzor92 commented
https://github.com/logicalclocks/hops-testing-ee/pull/152

2020-08-31 08:59 UTC, tkakantousis approved these changes

2020-08-31 09:04 UTC, merged