[HOPSWORKS-1918] Spark executor memory not modifiable from UI when starting jupyter fix
logicalclocks/hopsworks-chef pull request #498
Opened 2020-09-18 08:49 UTC by gibchikafa

https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-1918

2020-10-14 20:29 UTC, SirOibaf requested changes

2020-10-14 20:29 UTC, SirOibaf commented on templates/default/sql/dml/undo/1.4.0__undo.sql.erb
> +DELETE FROM `hopsworks`.`variables` WHERE `id`='max_env_yml_byte_size';~
Please restore the 1.4.0 to it's original value.

2020-10-19 14:53 UTC, tkakantousis approved these changes

2020-10-21 13:11 UTC, tkakantousis approved these changes

2020-10-21 13:12 UTC, merged