[HOPSWORKS-2025] Delete job executions
logicalclocks/hopsworks-chef pull request #501
Opened 2020-09-24 17:06 UTC by tkakantousis

We need this for integration tests in ruby

2020-09-29 09:19 UTC, robzor92 requested changes

2020-09-29 09:19 UTC, robzor92 commented on templates/default/sql/dml/2.0.0.sql.erb
> +REPLACE INTO `hopsworks`.`variables`(`id`, `value`) VALUES ("rmyarn_user", "<%= node['hops']['rm']['user'] %>");
Missing the undo.

2020-09-29 12:38 UTC, tkakantousis commented on templates/default/sql/dml/2.0.0.sql.erb
> +REPLACE INTO `hopsworks`.`variables`(`id`, `value`) VALUES ("rmyarn_user", "<%= node['hops']['rm']['user'] %>");
fixed

2020-10-01 13:29 UTC, robzor92 approved these changes

2020-10-01 15:21 UTC, merged