[HOPSWORKS-1374] Add Hudi API to HSFS and commits to the FeatureStore metadata
logicalclocks/hopsworks-chef pull request #506
Opened 2020-10-01 12:03 UTC by davitbzh

2020-10-30 09:31 UTC, moritzmeister commented
Don't forget to add the UNDO operations for rolling back.

2020-10-30 21:26 UTC, SirOibaf requested changes

2020-10-30 21:26 UTC, SirOibaf commented on files/default/sql/ddl/2.0.0__initial_tables.sql
> +  `timetravel_format`              ENUM('HUDI', 'NONE') NOT NULL DEFAULT 'HUDI',
This should be an `INT`. The persistence in hopsworks-ee takes care of doing the conversion.

2020-10-30 21:26 UTC, SirOibaf commented on files/default/sql/ddl/2.0.0__initial_tables.sql
> +-- Table structure for table `on_demand_feature`
leftover change.

2020-10-30 21:26 UTC, SirOibaf commented on files/default/sql/ddl/2.0.0__initial_tables.sql
> +) ENGINE=ndbcluster DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;
Please fix the formatting here.

2020-10-31 10:01 UTC, SirOibaf approved these changes

2020-10-31 10:02 UTC, merged