[HOPSWORKS-2165] Support installing python libraries using requirements.txt
logicalclocks/hopsworks-chef pull request #536
Opened 2020-11-25 11:00 UTC by robzor92

2020-11-25 14:09 UTC, robzor92 commented
https://github.com/logicalclocks/hops-testing-ee/pull/240

2020-11-25 21:05 UTC, tkakantousis requested changes

2020-11-25 21:05 UTC, tkakantousis commented on files/default/sql/ddl/updates/2.1.0.sql
> +ALTER TABLE `hopsworks`.`conda_commands` CHANGE `environment_yml` `environment_file` VARCHAR(10000) COLLATE latin1_general_cs DEFAULT NULL;
in the initial tables it is 1000.

2020-11-26 09:29 UTC, robzor92 commented on files/default/sql/ddl/updates/2.1.0.sql
> +ALTER TABLE `hopsworks`.`conda_commands` CHANGE `environment_yml` `environment_file` VARCHAR(10000) COLLATE latin1_general_cs DEFAULT NULL;
fixed

2020-11-26 09:32 UTC, tkakantousis approved these changes

2020-12-01 12:48 UTC, merged