issue#396
logicalclocks/hopsworks-chef pull request #554
Opened 2021-01-19 15:14 UTC by ErmiasG

2021-01-19 15:18 UTC, ErmiasG commented
logicalclocks/hops-testing-ee/pull/272

2021-01-22 08:48 UTC, tkakantousis approved these changes
Do these changes affect oauth clients in already deployed hopsworks clusters?

2021-01-22 08:49 UTC, tkakantousis requested changes

2021-01-22 08:49 UTC, tkakantousis commented on files/default/sql/ddl/updates/undo/2.1.0__undo.sql
> +DROP TABLE `feature_store_connector`;
Is this deleted my mistake?

2021-01-22 11:19 UTC, tkakantousis approved these changes

2021-01-22 11:20 UTC, tkakantousis approved these changes

2021-01-22 11:36 UTC, merged