[HOPSWORKS-2314] snowflake connector
logicalclocks/hopsworks-chef pull request #563
Opened 2021-02-02 13:52 UTC by ErmiasG

2021-02-02 13:56 UTC, ErmiasG commented
logicalclocks/hops-testing-ee/pull/279

2021-02-10 14:00 UTC, SirOibaf requested changes

2021-02-10 14:00 UTC, SirOibaf commented on files/default/sql/ddl/updates/undo/2.1.0__undo.sql
> +
Please remove this line

2021-03-03 09:46 UTC, SirOibaf approved these changes

2021-03-03 09:47 UTC, merged