[HOPSWORKS-2543] add support to insert_stream() to ingest data into offline fs
logicalclocks/hopsworks-chef pull request #667
Opened 2021-09-29 19:50 UTC by davitbzh

2021-09-29 20:07 UTC, SirOibaf requested changes

2021-09-29 20:07 UTC, SirOibaf commented on templates/default/sql/dml/2.1.0.sql.erb
> +REPLACE INTO `hopsworks`.`variables`(`id`, `value`) VALUES ("fs_py_job_util", "hdfs:///user/<%= node['hadoop_spark']['user'] %>/hsfs_utils-<%= node['hadoop_spark']['hsfs']['utils']['version'] %>.py")
This is not how these files work, you need to put your changes in the 3.0.0 files.

2022-02-10 10:34 UTC, moritzmeister commented on files/default/sql/ddl/updates/undo/2.6.0__undo.sql
> +ALTER TABLE `hopsworks`.`feature_group` DROP CONSTRAINT `stream_feature_group_fk`;
Did you test this? I believe you have to drop the Key and Constraint first, and drop the column last.

2022-03-14 09:20 UTC, moritzmeister approved these changes

2022-03-14 10:46 UTC, SirOibaf approved these changes

2022-03-14 10:59 UTC, merged