[HOPSWORKS-2877] Add ModelFeature table
logicalclocks/hopsworks-chef pull request #708
Opened 2022-01-03 10:01 UTC by kennethmhc

related to https://github.com/logicalclocks/hopsworks-ee/pull/747

2022-02-15 11:06 UTC, kennethmhc commented on files/default/sql/ddl/updates/2.5.0.sql
> +ALTER TABLE `hopsworks`.`training_dataset` ADD FOREIGN KEY `td_model_feature_fk` (`model_feature_id`) REFERENCES
We need it in `feature_view` table, but we can add it when implementing `TransformationResource`

2022-02-18 12:35 UTC, moritzmeister requested changes

2022-02-18 13:49 UTC, kennethmhc commented
do you mean https://github.com/logicalclocks/hopsworks-chef/blob/f120c3a00aea966eb3a3c5557d0cbcbf06df4e8c/files/default/sql/ddl/updates/undo/2.6.0__undo.sql#L2 and https://github.com/logicalclocks/hopsworks-chef/blob/f120c3a00aea966eb3a3c5557d0cbcbf06df4e8c/files/default/sql/ddl/updates/2.6.0.sql#L21 ?

2022-02-21 09:22 UTC, moritzmeister commented
@kennethmhc ah maybe I didn't see the drop column statements sinc they are in the same row :)

2022-02-21 09:23 UTC, moritzmeister approved these changes

2022-02-22 15:44 UTC, merged