[HWORKS-220] zip/unzip
logicalclocks/hopsworks-chef pull request #855
Opened 2022-11-29 15:13 UTC by ErmiasG

2022-11-29 15:14 UTC, ErmiasG commented
https://github.com/logicalclocks/hops-testing-ee/pull/582

2023-01-27 08:17 UTC, SirOibaf requested changes
We can also remove `dtrx` from the hops-system conda environment:
- https://github.com/logicalclocks/conda-chef/blob/05e8f38794f84af433cd3650e58948496fd1976c/templates/default/hops-system-environment.yml.erb#L56
-

2023-01-27 08:17 UTC, SirOibaf commented on files/default/sql/ddl/3.1.0__initial_tables.sql
> -) ENGINE=ndbcluster DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;
Can you restore this file to the master version?

2023-02-02 16:07 UTC, SirOibaf approved these changes

2023-02-08 08:47 UTC, merged