[FSTORE-684] Job scheduling
logicalclocks/hopsworks-chef pull request #892
Opened 2023-03-06 09:38 UTC by kennethmhc

2023-03-06 15:45 UTC, vatj approved these changes

2023-03-09 10:16 UTC, javierdlrm requested changes

2023-03-09 10:16 UTC, javierdlrm commented on files/default/sql/ddl/updates/undo/3.2.0__undo.sql
> +<<<<<<< HEAD
Leftover

2023-03-09 10:18 UTC, javierdlrm commented on files/default/sql/ddl/3.2.0__initial_tables.sql
> +                                              `job_frequency` varchar(20) NOT NULL,
Can you fix the indentation here please?

2023-03-09 12:32 UTC, kennethmhc commented
@javierdlrm fixed your comments.

2023-03-15 21:34 UTC, vatj approved these changes

2023-03-15 21:34 UTC, merged